### ISSUE TITLE
Enums with a value other than string cannot be loaded from the database

### ISSUE THREAD

**Issue by Erikvv** [acelaya/doctrine-enum-type#9]
They are converted to strings when saving and after loading Enum::isValid returns false.

I did this hack to make it work:

```php
<?php 

use MyCLabs\Enum\Enum;

class Status extends Enum
{
    const TEN = 10;
    const TWENTY = 20;

    public function __construct($value)
    {
        parent::__construct((int)$value);
    }

    public static function isValid($value)
    {
        return parent::isValid((int)$value);
    }
}
```

Maybe we can create a second type specifically for integer-only enums?

**Comment by acelaya** [comment]
Hmmm...

This is a tricky edge case.

Currently, there's no way to know which type the value used to have before persisting it. After reading it from the database, it is always a string.

Maybe I could think on a way to allow users to define the type of the enum values. However, if you use different types, it could fail anyway.

I could also serialize the value in a way that once deserialized, the system knows how to cast to a proper type, but it would be too intrusive, and will also introduce a BC break.

You have probably applied the simplest workaround possible, but another way would be defining your own column type and overwritting the `convertToPHPValue` method.

```php
class IntPhpEnumType extends PhpEnumType
{
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        if ($value === null) {
            return null;
        }
        
        return parent::convertToPHPValue((int) $value, $platform);
    }
}
```

Then use this type to register your int enums. If you have more than one enum with int values, this will avoid code duplication.

```php
IntPhpEnumType::registerEnumType(Status::class);
```

I will leave this open for now, in case I find (or anyone finds) a better solution, but don't expect this to be fixed in the near future.

**Comment by acelaya** [comment]
I'm including a new feature on next release which will allow Enumerations to define static methods whith the casting logic.

This way, you will be able to define your enumeration like this:

```php
<?php 

use MyCLabs\Enum\Enum;

class Status extends Enum
{
    const TEN = 10;
    const TWENTY = 20;

    public static function castFromDatabase($value)
    {
        return (int) $value;
    }
}
```

The `castFromDatabase` gets automatically called if defined when parsing the value from the database to the enumeration, before calling `isValid` or the contructor.

**Comment by acelaya** [comment]
I'm still thinking if the method should be called `castFromDatabase`. There's a similar one called `castToDatabase` which does the reverse operation if needed.

However, those names will couple the enumeration with an external concept, like the fact that you will persist the value in a database. I will try to think in something better before releasing the new version. Suggestions are welcome :-)

**Comment by acelaya** [comment]
I think I'm going to use the names `castValueIn` (as in cast the value "in", from the outside, the database) and `castValueOut` (as in cast the value to the outside).
